### ISSUE TITLE
EPIC: kickstart the open data lab

### ISSUE THREAD

**Issue by wmelder** [beeldengeluid/data.beeldengeluid.nl#64]
**Context**
Deze Epic beschrijft hoe we vanuit de huidige kennis en infrastructuur komen tot een werkende oplossing die het mogelijk maakt om de vraag naar de data van Beeld en Geluid in een open omgeving. 

Hierbij moet rekening gehouden worden met vooral de informatievoorziening richting het netwerk van digitale erfgoedinstellingen waar beeld en Geluid deel van uit maakt. Zie [overzichtsplaatje](https://github.com/beeldengeluid/opendatalab/wiki/Architectuurplaatje-Open-Data-Lab)

Verder moet er ook goed gekeken worden naar huidige oplossingen ne de mogelijkheden en beperkingen daarvan. 

**Taken**

## DAAN als LD: geschikt voor het open data lab (cc0 & schema.org)

**Doel**: Perfectioneren van het DAAN LD formaat tbv het ODL en een monster (LD files) op te leveren voor verdere ontwikkelingen.

- [x] perfectioneer de **cc0** versie in schema.org formaat middels de LOD server aan te sluiten op de **Flexstore API**. zie [deze issue](https://github.com/beeldengeluid/beng-lod-server/issues/106)
- [x] implementeer een simpel scriptje om een LD file dump (**monster**) te maken op basis van de LOD server. zie [issue hier](https://github.com/beeldengeluid/lod-importer/issues/17)
COMMENT WM: uitzoeken [hdt ](https://www.rdfhdt.org/)dump 
- [x] publiceer het **monster** op in de opendatalab GH (ook voor devops)
COMMENT WM: Het lijkt me niet zinvol om het **monster** op GH te plaatsen, omdat het data is. En heel veel data. Een link naar een file op een server moet voldoende zijn.
- [x] stel het NOB op de hoogte van het **monster**
- [x] (optioneel) pas [profile negotiation](https://www.w3.org/TR/dx-prof-conneg/) toe om beide schema.org en het B&G schema opvraagbaar te maken

## DAAN LD in een triple store (devops)

**Doel**: automatisch uitrollen van VMs met cliopatria triple stores + het geautomatiseerd importeren van linked data files

- [x] beeldengeluid/labs.beeldengeluid.nl#180
- [x] importeer het **monster** (via GH) in de cliopatria store
COMMENT WM: ik zie geen toegevoegde waarde om dit via GH te doen. Een gewone file link is voldoende. Suggestie: publiceer de file link op de CKAN instance van de mediasuite. Dan kunnen we daar ook de updates bijhouden.
- [x] gebruik postman om de SPARQL endpoint te testen (met een query die iets uit het **monster** opdiept)
- [ ] gebruik postman om de service te monitoren

## DAAN cc0 collectie gekoppeld aan search API (Elasticsearch)

**Doel**: in ODL is de DAAN beschikbaar als ES collectie, welke via de search API doorzocht kan worden. De `daan-catalogue-aggr` index dient als basis (wordt gevuld via de DAAN importer).

- [ ] onderzoek of het nodig is `daan-catalogue-aggr` te filteren of dat het nodig is een alias aan te maken om bepaalde resources uit te sluiten
- [ ] implementeer een nieuwe search API mapping (voor een nieuwe indexnaam `daan-catalogue-aggr-cc0`) die ervoor zorgt dat de geretourneerde resources **cc0** zijn (b.v. omschrijvingen inkorten en bepaalde velden uitsluiten)
- [ ] reindex de nieuwe alias (of de hele index) naar het AWS ES7 cluster naar het nieuwe `daan-catalogue-aggr-cc0`

## Implementatie DAAN LD importer

**Doel**: lange termijn voorziening bouwen welke LD kan voorzien welke **in sync** is met de DAAN catalogus

- [x] implementeer een nieuwe importer die gebruik maakt van dezelfde **cc0 mapping** welke gebruikt is bij de LOD server koppeling met de flexstore
- [ ] zorg dat de importer automatisch gedeployed wordt via GitHub actions
- [x] zorg dat de output eenvoudigweg in LD files wordt opgeslagen OF direct in een AWS triplestore
- [ ] verzin een manier om om te gaan met binnenkomende **updates en deletes** (hoe wijzig je reeds opgeslagen triples in files; bij triplestore wel vrij eenvoudig)

## DAAN geaggregeerde index GTAA links fixen

**Doel**: Op dit moment zijn er geen GTAA URIs aanwezig in de `daan-catalogue-aggr` index die door de DAAN importer wordt gevuld... Voor een betere link met het LD werk is het wenselijk deze URIs wel te hebben.

- [x] pas de DAAN importer aan, zodat de URIs standaard worden meegenomen
- [x] implementeer een script dat ontbrekende URIs kan bijvoegen in de index 
- [ ] zorg dat de index_template (mapping) wordt bijgewerkt

## B&G LOD server voor algemeen publiek

**Doel**: Resolven van B&G DAAN URIs voor het algemene publiek. **Waarschijnlijk pas op te leveren als de kopie van de Flexstore beschikbaar is**

- [x] zorg dat de LOD server is aangesloten op de kopie van de Flexstore
- [x] zorg ervoor dat er een duidelijke afspraak is dat de kopie Flexstore gekoppeld mag worden tbv het ODL
- [x] test het geheel binnen het domein data.rdlabs.beeldengeluid.nl (in AWS in het ODL)
- [x] zorg dat het allemaal draait op HTTPS

**Finale versie**
- [x] zorg dat het data.beeldengeluid.nl domein gekoppeld is aan de LOD server
